apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
    sonarqube.org/project-key: Gempayroll_BETA
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
