node('image_builder_trivy') { 
   stage('code-checkout') {
         dir ('hpipe_backend') {
         checkout([$class: 'GitSCM', branches: [[name: '*/development']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg:  [], \
userRemoteConfigs: [[credentialsId: 'admingithub', url: 'git@github.com:gem-aman/backstage-python.git']]])
         }
    }
  try {
   stage('Build_image') {
            dir ('hpipe_backend') {
              container('docker-image-builder-trivy') {
                withCredentials([usernamePassword(credentialsId: 'docker_registry', passwordVariable: 'docker_pass', usernameVariable: 'docker_user')]) {
              sh 'docker image build -f DockerFile -t registry-np.geminisolutions.com/backstage-python .'
                 
	}
                   sh '''docker login -u $docker_user -p $docker_pass https://registry-np.geminisolutions.com'''
              sh 'docker push registry-np.geminisolutions.com/backstage-python'
              sh 'docker push registry-np.geminisolutions.com/backstage-python'
           }
         }
        }
        stage('Deployment_stage') {
               dir ('hpipe_backend') {
                   container('docker-image-builder-trivy') {
                   kubeconfig(credentialsId: 'KubeConfigCred') {
                   sh '/usr/local/bin/kubectl apply -f Deployment_dev.yaml -n dev'
                   sh '/usr/local/bin/kubectl rollout restart Deployment backstage-python -n dev'

                   }
                   }
               }
           }
      }
  } finally {
     //sh 'echo current_image="registry-np.geminisolutions.com/hpipe/hpipe_backend/hpipe:1.0-$BUILD_NUMBER" > build.properties'
     //archiveArtifacts artifacts: 'build.properties', onlyIfSuccessful: true
  }